updated

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,8 +12,8 @@ jobs:
       - name: Run a one-line script
         run: echo "first practice"
 
-      # - name: Simulate an error
-      # run: echo "About to fail" ; exit 1
+      - name: Simulate an error
+     run: echo "About to fail" ; exit 1
 
       - name: Another greeting
         run: echo "first task completed"
